parameters:
    # Adds a fallback APP_VERSION if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(APP_VERSION): ''

twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - form/fields.html.twig
    globals:
        app_version: '%env(APP_VERSION)%'
