<?php

namespace AppBundle\Repository;

/**
 * BiologicalOriginCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiologicalOriginCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
