<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * BiologicalOriginCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiologicalOriginCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $query = $this->createQueryBuilder('category')
            ->leftJoin('category.team', 'team')
                ->addSelect('team')
            ->orderBy('team.name', 'ASC')
            ->addOrderBy('category.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function findAllAuthorizedForCurrentUser(User $user)
    {
        $query = $this->createQueryBuilder('category')
            ->leftJoin('category.team', 'team')
            ->addSelect('team')
            ->leftJoin('team.members', 'members')
            ->where('members = :user')
                ->setParameter('user', $user)
            ->orderBy('team.name', 'ASC')
            ->addOrderBy('category.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
