<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;

/**
 * genBankFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenBankFileRepository extends \Doctrine\ORM\EntityRepository
{
}
