<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;

/**
 * genBankFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenBankFileRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByTeamAndName(Team $team, $autoName)
    {
        $query = $this->createQueryBuilder('genBankFile')
            ->leftJoin('genBankFile.plasmid', 'plasmid')
            ->where('plasmid.team = :team')
            ->andWhere('plasmid.autoName = :autoName')
            ->setParameters([
                'team' => $team,
                'autoName' => $autoName,
            ])
            ->getQuery()
        ;

        return $query->getOneOrNullResult();
    }
}
