<?php

namespace AppBundle\Repository;

/**
 * GenusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenusRepository extends \Doctrine\ORM\EntityRepository
{
}
