<?php

namespace AppBundle\Repository;

/**
 * GMORepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GmoStrainRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithSpecies()
    {
        $query = $this->createQueryBuilder('gmo')
            ->leftJoin('gmo.species', 's')
                ->addSelect('s')
            ->leftJoin('s.genus', 'g')
                ->addSelect('g')
            ->getQuery();

        return $query->getResult();
    }
}
