<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;
use AppBundle\Entity\User;

/**
 * PlasmidRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlasmidRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForUser(User $user)
    {
        $query = $this->createQueryBuilder('plasmid')
            ->leftJoin('plasmid.team', 'team')
            ->leftJoin('team.members', 'members')
            ->where('members = :user')
                ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();
    }

    public function findOneWithAll($id)
    {
        $query = $this->createQueryBuilder('plasmid')
            ->leftJoin('plasmid.strainPlasmids', 'strainPlasmids')
                ->addSelect('strainPlasmids')
            ->leftJoin('strainPlasmids.strain', 'strain')
                ->addSelect('strain')
            ->leftJoin('strain.team', 'team')
                ->addSelect('team')
            ->leftJoin('team.members', 'members')
                ->addSelect('members')
            ->leftJoin('plasmid.primers', 'primers')
                ->addSelect('primers')
            ->where('plasmid.id = :id')
                ->setParameter('id', $id)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function findOneByTeamAndNameWithFile(Team $team, $autoName)
    {
        $query = $this->createQueryBuilder('plasmid')
            ->leftJoin('plasmid.genBankFile', 'genBankFile')
            ->where('plasmid.team = :team')
            ->andWhere('plasmid.autoName = :autoName')
            ->setParameters([
                'team' => $team,
                'autoName' => $autoName,
            ])
            ->getQuery()
        ;

        return $query->getOneOrNullResult();
    }
}
