<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * PrimerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForUser(User $user)
    {
        $query = $this->createQueryBuilder('primer')
            ->leftJoin('primer.team', 'team')
            ->leftJoin('team.members', 'members')
            ->where('members = :user')
            ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();
    }
}
