<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Team;

/**
 * ProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductsWarning(Team $team)
    {
        $query = $this->createQueryBuilder('product')
            ->where('product.team = :team')
                ->setParameter('team', $team)
            ->andWhere('product.stock <= product.stockWarningAlert')
            ->leftJoin('product.seller', 'seller')
                ->addSelect('seller')
            ->orderBy('seller.name', 'ASC')
            ->addOrderBy('product.stock', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
