<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * ProjectRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllAuthorizedForCurrentUser(User $user)
    {
        $query = $this->createQueryBuilder('project')
            ->leftJoin('project.members', 'members')
            ->leftJoin('project.teams', 'teams')
            ->leftJoin('teams.administrators', 'administrators')
            ->where('members = :user')
            ->orWhere('administrators = :user')
                ->setParameter('user', $user)
            ->getQuery();

        return $query->getResult();
    }
}
