<?php

namespace AppBundle\Repository;

/**
 * SpeciesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{
    public function createSearchQueryBuilder($entityAlias)
    {
        $qb = $this->createQueryBuilder($entityAlias);

        $qb->select($entityAlias, 's')
            ->innerJoin($entityAlias.'.genus', 's')
        ;

        return $qb;
    }

    public function findOneWithGenus($species)
    {
        $query = $this->createQueryBuilder('species')
            ->innerJoin('species.genus', 'genus')
                ->addSelect('genus')
            ->where('species = :species')
            ->setParameter('species', $species)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function findOneWithGenusAndSynonyms($species)
    {
        $query = $this->createQueryBuilder('species')
            ->innerJoin('species.genus', 'genus')
                ->addSelect('genus')
            ->innerJoin('species.synonyms', 'synonyms')
                ->addSelect('synonyms')
            ->where('species = :species')
                ->setParameter('species', $species)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
