<?php

namespace AppBundle\Repository;

/**
 * SpeciesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithGenus()
    {
        $query = $this->createQueryBuilder('species')
            ->leftJoin('species.genus', 'genus')
                ->addSelect('genus')
            ->orderBy('genus.name', 'ASC')
            ->addOrderBy('species.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function findOneWithGenus($species)
    {
        $query = $this->createQueryBuilder('species')
            ->leftJoin('species.genus', 'genus')
                ->addSelect('genus')
            ->where('species = :species')
            ->setParameter('species', $species)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
