<?php

namespace AppBundle\Repository;

/**
 * SpeciesRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeciesRepository extends \Doctrine\ORM\EntityRepository
{
    public function createSearchQueryBuilder($entityAlias)
    {
        $qb = $this->createQueryBuilder($entityAlias);

        $qb->select($entityAlias, 's')
            ->leftJoin($entityAlias.'.genus', 's')
        ;

        return $qb;
    }

    public function findOneWithGenus($slug)
    {
        $query = $this->createQueryBuilder('species')
            ->leftJoin('species.genus', 'genus')
                ->addSelect('genus')
            ->where('species.slug = :slug')
            ->setParameter('slug', $slug)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function findOneWithGenusAndSynonyms($slug)
    {
        $query = $this->createQueryBuilder('species')
            ->leftJoin('species.genus', 'genus')
                ->addSelect('genus')
            ->leftJoin('species.synonyms', 'synonyms')
                ->addSelect('synonyms')
            ->where('species.slug = :slug')
                ->setParameter('slug', $slug)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
