<?php

namespace AppBundle\Repository;

/**
 * StrainPlasmidRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StrainPlasmidRepository extends \Doctrine\ORM\EntityRepository
{
}
