<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * TeamRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllWithMembers()
    {
        $query = $this->createQueryBuilder('team')
            ->innerJoin('team.administrators', 'administrators')
                ->addSelect('administrators')
            ->innerJoin('team.members', 'members')
                ->addSelect('members')
            ->orderBy('team.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function findOneWithMembers($team)
    {
        $query = $this->createQueryBuilder('team')
            ->innerJoin('team.administrators', 'administrators')
                ->addSelect('administrators')
            ->innerJoin('team.members', 'members')
                ->addSelect('members')
            ->where('team = :team')
                ->setParameter('team', $team)
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function findAllForUser(User $user)
    {
        $query = $this->createQueryBuilder('team')
            ->innerJoin('team.members', 'members')
            ->innerJoin('team.administrators', 'administrators')
                ->addSelect('administrators')
            ->where('members = :user')
                ->setParameter('user', $user)
            ->orderBy('team.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
