<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * TypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        $query = $this->createQueryBuilder('type')
            ->leftJoin('type.team', 'teams')
                ->addSelect('teams')
            ->orderBy('teams.name', 'ASC')
            ->addOrderBy('type.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }

    public function findAllAuthorizedForCurrentUser(User $user)
    {
        $query = $this->createQueryBuilder('type')
            ->leftJoin('type.team', 'teams')
                ->addSelect('teams')
            ->leftJoin('teams.members', 'members')
            ->where('members = :user')
                ->setParameter('user', $user)
            ->orderBy('teams.name', 'ASC')
            //->addOrderBy('type.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
