<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * TypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeRepository extends \Doctrine\ORM\EntityRepository
{
}
