<?php

namespace AppBundle\Repository;

/**
 * WildRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WildStrainRepository extends \Doctrine\ORM\EntityRepository
{
}
