<?php

/*
 * Copyright 2016-2018 Mathieu Piot.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace App\Repository;

/**
 * BoxRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoxRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneWithStrains($boxId)
    {
        $query = $this->createQueryBuilder('box')
            ->leftJoin('box.tubes', 'tubes')
                ->addSelect('tubes')
            ->leftJoin('tubes.strain', 'strain')
                ->addSelect('strain')
            ->where('box.id = :boxId')
                ->setParameter('boxId', $boxId)
            ->orderBy('tubes.cell', 'ASC')
            ->getQuery();

        return $query->getOneOrNullResult();
    }

    public function findForCSVExport($box)
    {
        $query = $this->createQueryBuilder('box')
            ->leftJoin('box.tubes', 'tubes')
                ->addSelect('tubes')
                ->orderBy('tubes.cell', 'ASC')
            ->leftJoin('tubes.strain', 'strain')
                ->addSelect('strain')
            ->leftJoin('strain.species', 'species')
                ->addSelect('species')
            ->leftJoin('species.genus', 'genus')
                ->addSelect('genus')
            ->leftJoin('strain.strainPlasmids', 'strainPlasmids')
                ->addSelect('strainPlasmids')
            ->leftJoin('strainPlasmids.plasmid', 'strain_plasmid')
                ->addSelect('strain_plasmid')
            ->leftJoin('strain.parents', 'strain_parents')
                ->addSelect('strain_parents')
            ->leftJoin('tubes.plasmid', 'plasmid')
                ->addSelect('plasmid')
            ->leftJoin('plasmid.primers', 'plasmid_primers')
                ->addSelect('plasmid_primers')
            ->leftJoin('tubes.primer', 'primer')
                ->addSelect('primer')
            ->leftJoin('primer.plasmids', 'primer_plasmids')
                ->addSelect('primer_plasmids')
            ->where('box = :box')
            ->setParameter('box', $box)
            ->getQuery();

        return $query->getOneOrNullResult();
    }
}
