<?php

namespace App\Repository;

/**
 * genBankFileRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenBankFileRepository extends \Doctrine\ORM\EntityRepository
{
}
