<?php

namespace App\Repository;

use App\Entity\Group;

/**
 * ProductRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductsWarning(Group $group)
    {
        $query = $this->createQueryBuilder('product')
            ->where('product.group = :group')
                ->setParameter('group', $group)
            ->andWhere('product.stock <= product.stockWarningAlert')
            ->leftJoin('product.seller', 'seller')
                ->addSelect('seller')
            ->orderBy('seller.name', 'ASC')
            ->addOrderBy('product.stock', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
