<?php

namespace App\Repository;

/**
 * TubeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TubeRepository extends \Doctrine\ORM\EntityRepository
{
}
