#!/bin/bash

docker pull $APP_DOCKER_IMAGE_NAME:latest
docker build --cache-from=$APP_DOCKER_IMAGE_NAME:latest -t $APP_DOCKER_IMAGE_NAME:$TRAVIS_TAG .
docker tag $APP_DOCKER_IMAGE_NAME:$TRAVIS_TAG $APP_DOCKER_IMAGE_NAME:latest
docker push $APP_DOCKER_IMAGE_NAME:$TRAVIS_TAG
docker push $APP_DOCKER_IMAGE_NAME:latest
