FROM docker.elastic.co/elasticsearch/elasticsearch:5.2.2

#RUN /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head
#RUN /usr/share/elasticsearch/bin/plugin install royrusso/elasticsearch-HQ
